export const Events = {
  LIST_SCROLL_TO_TOP:
    'REACT-NATIVE-HEAD-TAB-VIEW-FLASHLIST-SUPPORT-LIST-SCROLL-TO-TOP-EVENT',
  IGNORE_SCROLL_ENABLE: 'IGNORE-SCROLL-ENABLE',
};

export const IgnoreScrollEnableType = {
  ON_TAB_PRESSED: 'ON-TAB-PRESSED',
  ON_SWIPE_START: 'ON-SWIPE-START',
  ON_SWIPE_END: 'ON-SWIPE-END',
};
